######################## default configuration ####################
baseURL = "https://skinlush.net/"
title = "SkinLush.net | Tu guía de maquillaje y cosmetica"
theme = "geeky-hugo"
languageName = "De"
languageCode = "de-DE"
# post pagination
pagination.pagerSize = "6"
# post excerpt
summaryLength = "5"
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en

# disable language
disableLanguages = []

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 95
anchor = "Smart"
resampleFilter = "Lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"


############################ sitemap  ###########################
[sitemap]
  changeFreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0


############################ exclude from sitemap  ###########################
[params]
taxonomiesExcludedFromSitemap = ["tags", "categories"]